### PR TITLE
Closes #35: avoid index out of range when decompressor needs input an…

### LINKED ISSUE #35: index out of range when availableIn=0 and r.needOutput is true
Trace:

```
r.bufferRead = 131072, r.availableIn = 0, inputPosition = 131072, buffer len = 131072
panic: runtime error: index out of range

goroutine 140 [running]:
github.com/itchio/butler/vendor/gopkg.in/kothar/brotli-go.v0/dec.(*BrotliReader).Read(0xc42016e150, 0xc42011d640, 0x1, 0x1, 0x1, 0x0, 0x0)
        /home/amos/go/src/github.com/itchio/butler/vendor/gopkg.in/kothar/brotli-go.v0/dec/decode.go:143 +0x62d
github.com/itchio/butler/vendor/github.com/itchio/wharf/wire.(*ReadContext).ReadByte(0xc42001b980, 0x10080, 0x0, 0x0)
        /home/amos/go/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/wire/read.go:33 +0x52
encoding/binary.ReadUvarint(0xf915c0, 0xc42001b980, 0x4138ed, 0x9ac080, 0xc420010300)
        /usr/local/go/src/encoding/binary/varint.go:110 +0x4a
github.com/itchio/butler/vendor/github.com/itchio/wharf/wire.(*ReadContext).ReadMessage(0xc42001b980, 0xf97bc0, 0xc4201961c0, 0x0, 0x0)
        /home/amos/go/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/wire/read.go:63 +0x3b
github.com/itchio/butler/vendor/github.com/itchio/wharf/pwr.readOps(0xc42001b980, 0xc420010300, 0xc4200102a0)
        /home/amos/go/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/pwr/apply.go:936 +0x114
created by github.com/itchio/butler/vendor/github.com/itchio/wharf/pwr.(*ApplyContext).patchAll
        /home/amos/go/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/pwr/apply.go:466 +0x6ff
amos@poppy:~/butler-tests/possessed$

```

Offending bit of code:

```go
                if r.availableIn > 0 || r.needOutput {
                        // Decompress
                        inputPosition := r.bufferRead - int(r.availableIn)
                        fmt.Printf("r.bufferRead = %d, r.availableIn = %d, inputPosition = %d, buffer len = %d\n", r.bufferRead, r.availableIn, inputPosition, len(r.buffer));
                        result := C.BrotliDecompressStream_Wrapper(
                                &r.availableIn,
                                (*C.uint8_t)(unsafe.Pointer(&r.buffer[inputPosition])),
                                &availableOut,
                                (*C.uint8_t)(unsafe.Pointer(&p[0])),
                                &r.totalOut,
                                (*C.BrotliState)(r.state),
                        )

                        n = maxOutput - int(availableOut)
```

I think the issue is that.. `&r.buffer[inputPosition]` is valid in C because there's no bound check going on, but in golang there is, and it fails. I wonder if `unsafe.Pointer(&r.buffer)+inputPosition` would work (and be faster!

If that fails, maybe we can pass a null pointer instead in that very case.

I'm impressed this even happened though (I have a reproducible test case here, but it involves a >2GB file right now), I've been using brotli-go in production for 1yr+ without issues :)

### PR DESCRIPTION
**Pull request by fasterthanlime**
…d we have no input available

See #35 for more details on the issue.

### CODE REVIEW

**Comment by fasterthanlime** [comment]
All tests pass on my machine :+1: let's see what Travis CI says.

**Comment by fasterthanlime** [comment]
Well looks like the golint issue is known: https://github.com/golang/lint/issues/213 - but I don't see why the Travis CI workers would have a busted $GOPATH though.

**Comment by fasterthanlime** [comment]
It might be worth bumping the CI version to the latest 1.5.x (or even an 1.6, 1.7, 1.8 version ?) to get the tests to pass. No pressure from here, I've deployed hotfixes locally

**Comment by kothar** [comment]
Thanks Amos, I've been meaning to look at the tests for a while. I've updated the configuration to test against 1.6.x onwards, which needed a little fiddling since Travis doesn't seem to have the latest go releases.

Do you want to try rebasing your PR onto master and see if everything passes? Just re-running the PR build doesn't seem to pick up the changes.

**Comment by fasterthanlime** [comment]
I messed up the rebase somehow but managed to push the changes again, let's see if it passes CI.

**Comment by fasterthanlime** [comment]
Well, some of the CI builds are still failing for mysterious reasons, they don't seem related to my change though.

**Comment by kothar** [comment]
Looks like go vet doesn't like:
``` go
nextIn := unsafe.Pointer(uintptr(0))
```

Points 2 and 3 in the Pointer documentation suggest that you can't convert an arbitrary integer to a pointer, only pointer -> uintptr -> pointer in a single expression

https://golang.org/pkg/unsafe/#Pointer

So, I think we need this instead:
``` go
nextIn := unsafe.Pointer(nil)
```

Which seems to pass the go vet check and all the tests.

**Comment by fasterthanlime** [comment]
> So, I think we need this instead:

Oh yeah, even better! The main point of my fix is:

There's a memory region like so:

```
[      ]
\     /
```

in C, it's legal to pass this address and a size of 0:

```
[      ]
       X
```

But not in golang where it's an index out of bounds error, since we use slice indexing to make an address.

So, nil is great, I'm not sure why I didn't think of it :)

**Comment by kothar** [comment]
Would you like to switch to using nil, and then we can merge this PR?

Thanks,
Mike.

**Comment by fasterthanlime** [comment]
> Would you like to switch to using nil, and then we can merge this PR?

Done! :shipit:

**Comment by kothar** [comment]
👍  Thanks :)

**Pull request merged**
